version: "2.1"

services:
  geth:
    # build: ./geth
    image: ethereum/client-go:stable
    command: --rpc --rpcaddr 0.0.0.0 --rpcvhosts "*" --rpccorsdomain "*" --rpcport 8545 --rpcapi "eth"
    ports:
      - 127.0.0.1:8545:8545
    healthcheck:
      test: geth attach http://127.0.0.1:8545
      interval: 5s
      timeout: 5s
      retries: 50
    volumes:
      - geth-vol:/root
    restart: on-failure
  watcher:
    build: ./watcher
    depends_on:
      geth:
        condition: service_healthy
    restart: on-failure
volumes:
  geth-vol:

